site_name: BurstFit Documentation
site_author: Devansh Agarwal, Kshitij Agarwal
docs_dir: build/content
site_description: 'BurstFit Documentation'
repo_name: burstfit
repo_url: https://github.com/thepetabyteproject/burstfit

theme:
  name: material
  palette:
    primary: black
  features:
    - search.highlight

nav:
  - Getting Started: index.md
  - BurstFit: BurstFit.ipynb
  - BurstData: BurstData.ipynb
  - BurstIO: BurstIO.ipynb
  - MCMC: MCMC.ipynb
  - BurstFit_custom: BurstFit_custom_function.ipynb
  - Reference API:
    - BurstFit: bustfit.md 
    - BurstData: burstfit.data.md
    - BurstIO: burstfit.io.md
    - MCMC: burstfit.mcmc.md
    - Model: burstfit.model.md
    - Utils:
      - Astro: burstfit.utils.astro.md
      - Functions: burstfit.utils.functions.md
      - Math: burstfit.utils.math.md
      - Misc: burstfit.utils.misc.md
      - Plotter: burstfit.utils.plotter.md

plugins:
  - search
  - mkdocs-jupyter:
      include_source: True

markdown_extensions:
  - codehilite
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
